<a href="https://colab.research.google.com/github/tiennvcs/EE6363_AdvancedML/blob/main/HW1/P3/Task_1_Stabilized_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import svd
from typing import List, Union

## SVD by Scipy

In [2]:
def standardSVD(A: np.ndarray) -> Union[np.ndarray, np.ndarray, np.ndarray]:
    U, S, Vt = svd(A)
    a = np.zeros(A.shape)
    np.fill_diagonal(a, S)
    S = a
    return U, S, Vt

In [3]:
# Test standard SVD function
A = np.array([
    [3, 2, 2],
    [2, 3, -2],
])
U, S, Vt = standardSVD(A)
print("Original matrix A: \n{}".format(A))
print("Left singular vectors (U): \n{}".format(U))
print("Singular values (S): \n{}".format(S))
print("Right singular vectors (Vt): \n{}".format(Vt))

Original matrix A: 
[[ 3  2  2]
 [ 2  3 -2]]
Left singular vectors (U): 
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular values (S): 
[[5. 0. 0.]
 [0. 3. 0.]]
Right singular vectors (Vt): 
[[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


In [4]:
def reconstructSVD(U, S, Vt) -> np.ndarray:
    return (U.dot(S)).dot(Vt)

In [5]:
B = reconstructSVD(U, S, Vt)
print("Reconstruct SVD: \n{}".format(B))

Reconstruct SVD: 
[[ 3.  2.  2.]
 [ 2.  3. -2.]]


## Task 1. Stablized SVD

In [6]:
def stablizedSVD(A: np.ndarray, epsilon=0.5) -> Union[np.ndarray, np.ndarray, np.ndarray]:
    # Call SVD from scipy
    U, S, Vt = standardSVD(A)
    # Find maximum k that satisfy S_{k, k}/S_{0, 0} >= epsilon
    k = 0
    while k < S.shape[0]:
        if S[k, k]/S[0, 0] < epsilon:
            break
        k += 1
    k = k -1
    # Gather columns of U to form new Us
    Us = U[:, 0:k+1]
    # Gather columns of S to form new Ss
    Ss = S[:k+1, :k+1]
    # Gather rows of Vt to form new Vts
    Vts = Vt[:k+1, :]
    return Us, Ss, Vts

In [7]:
A = np.array([
    [3, 1, 2],
    [1, 3, 1],
    [2, 1, 3],
])

In [8]:
# Apply standard SVD
U, S, Vt = standardSVD(A)

In [9]:
print("Original matrix A: \n{}".format(A))
print("Left singular vectors (U): \n{}".format(U))
print("Singular values (S): \n{}".format(S))
print("Right singular vectors (Vt): \n{}".format(Vt))

Original matrix A: 
[[3 1 2]
 [1 3 1]
 [2 1 3]]
Left singular vectors (U): 
[[-6.27963030e-01  3.25057584e-01 -7.07106781e-01]
 [-4.59700843e-01 -8.88073834e-01 -8.32667268e-17]
 [-6.27963030e-01  3.25057584e-01  7.07106781e-01]]
Singular values (S): 
[[5.73205081 0.         0.        ]
 [0.         2.26794919 0.        ]
 [0.         0.         1.        ]]
Right singular vectors (Vt): 
[[-6.27963030e-01 -4.59700843e-01 -6.27963030e-01]
 [ 3.25057584e-01 -8.88073834e-01  3.25057584e-01]
 [-7.07106781e-01  1.11022302e-16  7.07106781e-01]]


In [10]:
# Apply Stabilized SVD
Us, Ss, Vts = stablizedSVD(A, epsilon=0.3)

In [11]:
print("Original matrix A: \n{}".format(A))
print("Left singular vectors (Us): \n{}".format(Us))
print("Singular values (Ss): \n{}".format(Ss))
print("Right singular vectors (Vts): \n{}".format(Vts))

Original matrix A: 
[[3 1 2]
 [1 3 1]
 [2 1 3]]
Left singular vectors (Us): 
[[-0.62796303  0.32505758]
 [-0.45970084 -0.88807383]
 [-0.62796303  0.32505758]]
Singular values (Ss): 
[[5.73205081 0.        ]
 [0.         2.26794919]]
Right singular vectors (Vts): 
[[-0.62796303 -0.45970084 -0.62796303]
 [ 0.32505758 -0.88807383  0.32505758]]


$\rightarrow$ With $epsilon = 0.3$ the stablized SVD eliminates the third singular value $\sigma_3$  of S, i.e., $\sigma_3 = 1$ that do not satisfy condition $S_{k, k}/S_{1, 1} \ge 0.3$. It also eliminates some columns of $U$ to form new tall matrix $U_s$, eliminates some rows of $V$ to form new tall matrix $V^T_s$.



$\rightarrow$ Role of $\epsilon$: to control how many singular values (also how many columns of $U$ and $V$ remain after being cutdown) we want eliminate. If we set $\epsilon$ high, we want $U_s, V^T_s, S_s$ shorter (more compact).


$\rightarrow$  $\epsilon = 0$: because $S_{i,i} = \sigma_i \ge 0, \ \forall i$, hence $S_{i, i}/S_{1, 1} \ge 0 = \epsilon, \ \forall i$. It means we kept all singular values of $S$, therefore $U_s, S_s, V_s$ do not change anything. Or we can say, stabilized SVD become standard SVD.

$\rightarrow$ Why it named **stabilized** SVD: thanks to controlling parameter $ϵ$, we can control the output.



$\rightarrow$ When choose $\epsilon = 0$, stabilized SVD